config/routes.rb
Stretchpants::Application.routes.draw do
  resources :campers do
    collection do
      get 'search'
    end
  end

  root :to => 'campers#index'

end

app/models/camper.rb
class Camper
  include Tire::Model::Persistence

  property :name, :analyzer => 'keyword', :type => :string
  property :twitter, :type => :string
  property :city, :type => :string
  property :bio, :type => :string
  property :drink_count, :class => Integer, :default => 0, :type => :integer
  property :tags, :analyzer => 'keyword', :class => [String], :type => :string

  def id
    name.blank? ? nil : name.gsub(/ /,"_").downcase
  end

  def self.full_search(search_query, params)
    search do |search|
      search.query do |query|
        query.string search_query
      end

      search.sort do |sort|
        sort.by :name, 'asc'
     end

      unless params[:tags].blank?
        search.filter :term, :tags => params[:tags]
      end

      search.facet 'tags', :global => true do
        terms :tags
      end
    end
  end

  # If you were using ActiveRecord etc. instead you would include these:
  #include Tire::Model::Search
  #include Tire::Model::Callbacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/campers_controller.rb
class CampersController < ApplicationController
  def index
    @campers = params[:query].blank? ? Camper.all : Camper.search(params[:query].blank? ? "*" : params[:query].to_s)
  end

  def search
    query = params[:query].blank? ? "*" : params[:query].to_s
    @campers = Camper.full_search query, params.slice(:tags)
    render :index
  end

  def show
    @camper = Camper.find(params[:id].to_s)
  end

  def new
    @camper = Camper.new
  end

  def edit
    @camper = Camper.find(params[:id].to_s)
  end

  def update
    params[:camper][:tags] = params[:camper][:tags].gsub(/,/, ' ').split(' ')
    @camper = Camper.find(params[:id])
    @camper.update_attributes(params[:camper])
    redirect_to @camper
  end

  def create
    params[:camper][:tags] = params[:camper][:tags].gsub(/,/, ' ').split(' ')
    @camper = Camper.create(params[:camper])
    redirect_to @camper
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campers_helper.rb
module CampersHelper
end

app/views/campers/edit.html.haml
%h1="Edit #{@camper.name}"
= form_for @camper do |f|
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :twitter
    %br
    = f.text_field :twitter
  %p
    = f.label :city
    %br
    = f.text_field :city
  %p
    = f.label :drink_count
    %br
    = f.text_field :drink_count
  %p
    = f.label :tags
    %br
    = f.text_field :tags, :value => @camper.tags.join(", ")
  %p
    = f.label :bio
    %br
    = f.text_area :bio
  =f.submit

app/views/campers/index.html.haml
%h1 Campers

#search_forms
  %p
    = form_tag({:action => :index}, {:method => :get}) do
      = label_tag :query, "Search"
      = text_field_tag :query, params[:query]
      = submit_tag :go
  %p
    = form_tag({:action => :search}, {:method => :get}) do
      = label_tag :query, "Complex Search"
      = text_field_tag :query, params[:query]
      = submit_tag :complex_search
  %p
    = link_to "Tire me a new one", new_camper_path

#title
  - if params[:query]
    %h2="Campers matching #{params[:query]}"
  -else
    %h2 All of the things!
    %p All the json you could possibly want.

- if @campers.facets
  #facets
    %ul
      - @campers.facets.each do |k,v|
        %li
          = k
          %ul
            -v['terms'].each do |term|
              %li=link_to "#{term['term']} (#{term['count']})", params.merge(:tags => term['term'])
#campers
  -@campers.each do |c|
    %p
      =link_to "#{c.name}", c
      =link_to "Edit", edit_camper_path(c.id)
    %p=c.to_json

app/views/campers/new.html.haml
%h1 New Camper
= form_for @camper do |f|
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :twitter
    %br
    = f.text_field :twitter
  %p
    = f.label :city
    %br
    = f.text_field :city
  %p
    = f.label :drink_count
    %br
    = f.number_field :drink_count
  %p
    = f.label :tags
    %br
    = f.text_field :tags
  %p
    = f.label :bio
    %br
    = f.text_area :bio
  =f.submit

app/views/campers/show.html.haml
%h1=@camper.name
%p
  = link_to "Back to the campers list", campers_path
%p
  = link_to "Edit #{@camper.name}", edit_camper_path(@camper)
%p
  = @camper.as_json

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stretchpants</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>